version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: lint
          command: yarn run lint
      - run:
          name: flow-type-check
          command: yarn run flow
      - run:
          name: test
          command: yarn test
      - run:
          name: code-coverage
          command: yarn run coverage
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
