version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: yarn run coverage
      - run: ./cc-test-reporter after-build -t lcov --exit-code $?
